<?php
/**
* Replace all comments if you would like. Be sure to identify params, files and returns in your comments
*/

//Implements hook_node_view_alter()
function pro_101_custom_node_view_alter(&$build) {
  if(isset($build['#node'])) {
    $node = $build['#node'];
    if(!empty($node->nid)) {
      $build['#contextual_links']['node'] = array('node', array($node->nid));
    }
  }
}

function pro_101_custom_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user-login') {
    $form['pass']['#attributes']['autocomplete'] = 'off';
  }
}

/**
* Your module will use the subject as the main title and load the content from your function
*/
// function pro_101_block($op='list', $delta=0, $edit=array())
// {
// 	switch ($op) {
// 	case 'list':
// 	$blocks[0]['info'] = t('pro 101');
// 	return $blocks;
// 	case 'view':
// 	$blocks['subject'] = t('pro 101');
// 	$blocks['content'] = pro_101_block_content();
// 	return $blocks;
// 	}
// }
//
// /**
// * Your module should generate it's content here. This will be displayed within your module
// */
// function pro_101_block_content()
// {
// 	$content .= "Replace with your logic";
// 	return $content;
// }
//
// /**
// * This will allow you to restrict certain actions of the module to certain roles
// */
// function pro_101_perm()
// {
// 	return array('access pro_101','administer pro_101');
// }
//
// /**
// * This will provide users with more information about your module
// */
// function pro_101_hook_help($path, $arg)
// {
// 	switch($path) {
// 	case 'admin/help#pro_101':
// 		$output = t('Help Content Goes Here');
// 	return $output;
// 	}
// }
//
// /**
// * This will create an admin menu
// */
// function pro_101_menu()
// {
// 	$items = array ();
// 	$items['admin/settings/pro_101'] = array (
// 		'title' => t('pro 101'),
// 		'description' => t('Replace with admin setting description'),
// 		'page callback' => 'drupal_get_form',
// 		'page arguments' => array('pro_101_settings'),
// 		'access arguments' => array('administer pro_101'),
// 		'type' => MENU_NORMAL_ITEM,
// 	);
// 	return $items;
// }
//
// /**
// * This will construct the form used within the admin menu
// */
// function pro_101_settings()
// {
// 	$form['pro_101_general_settings'] = array(
// 		'#title' => t('General Settings'),
// 		'#type' => "fieldset",
// 		'#collapsible' => TRUE,
// 	);
// 	$form['pro_101_general_settings']['text'] = array(
// 		'#title' => t('Text'),
// 		'#type' => "fieldset",
// 		'#collapsible' => TRUE,
// 		'#collapsed' => FALSE,
// 	);
// 	$form['pro_101_general_settings']['text']['sample'] = array(
// 		'#title' => t('Sample'),
// 		'#type' => "textfield",
// 		'#size' => 45,
// 		'#maxlength' => 50,
// 		'#required' => FALSE,
// 		'#description' => t('Sample textfield and settings menu'),
// 		'#default_value' => variable_get('sample','Sample Text'),
// 	);
// 	return system_settings_form($form);
// }
